spring:
  application:
    name: eureka
eureka:
  client:
    #如果设置成false，unvialiable里就会有peer节点
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 1000

---
spring:
  profiles: eureka-7900
server:
  port: 7900
eureka:
  instance:
    hostname: eureka-7900

---
spring:
  profiles: eureka-7901
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901

---
spring:
  profiles: eureka-7902
server:
  port: 7902
eureka:
  instance:
    hostname: eureka-7902
